In [10]:
import numpy as np

# creates a 5 random-Gaussian variables store in array a
# this is a rank 1 array
a = np.random.randn(5)

In [11]:
print(a)

[-0.66366468 -1.39451102  0.41803832 -0.38531255 -0.37779638]


In [12]:
print(a.shape)

(5,)


In [13]:
print(a.T)

[-0.66366468 -1.39451102  0.41803832 -0.38531255 -0.37779638]


In [14]:
print(np.dot(a, a.T))

2.8510637039184386


In [15]:
# This is a (1,5) matrix
a = np.random.randn(5,1)
print(a)

[[-0.54149411]
 [ 0.69985854]
 [-0.41763361]
 [ 1.4829436 ]
 [-0.37209797]]


In [16]:
print(a.T)

[[-0.54149411  0.69985854 -0.41763361  1.4829436  -0.37209797]]


In [17]:
print(np.dot(a,a.T))

[[ 0.29321587 -0.37896928  0.22614614 -0.80300523  0.20148886]
 [-0.37896928  0.48980198 -0.29228445  1.03785075 -0.26041594]
 [ 0.22614614 -0.29228445  0.17441783 -0.61932709  0.15540062]
 [-0.80300523  1.03785075 -0.61932709  2.19912172 -0.5518003 ]
 [ 0.20148886 -0.26041594  0.15540062 -0.5518003   0.1384569 ]]
